### ISSUE TITLE
Grails 3.2.8 / build-test-data 3.0.1 Transaction doesn't flush when using build()

### ISSUE THREAD

**Issue by sgates** [longwa/build-test-data#73]
This behavior started recently, previously working tests started to break, so maybe because of a grails core change?

If I'm testing a service, and I build() a couple domain classes in the test, the service that then returns those objects (say, using list()) doesn't see them. If I manually re-save one of the objects with save(flush:true), or if I use any of the GORM methods like Person.count() or Person.list(), then the service will see the domain classes.

It's as if there is a transaction being held open after build() that I have to manually close. Wrapping the .build() in a withTransaction{} closure also works, so definitely seems transaction related. I can build & provide a sample application if needed.

(Sorry for all the edits! I should proof read first)

**Comment by jarl-dk** [comment]
I also ran into this problem...

**Comment by longwa** [comment]
I'm hoping some of this behavior is cleaned up with some of the Transactional rework with integration tests in 3.3.x and later.

I've seen this problem as well and tend to call flush as you did to fix it. I'm not sure it's a BTD problem specifically because it also seems to occur in cases where we are building objects manually.

**Comment by longwa** [comment]
Closing as this is more of a Grails/Test/Transactional issue. BTD just calls save() on the object and doesn't try to do any explicit flush or transaction management.
