### ISSUE TITLE
Long test setup when building objects referencing abstract classes

### ISSUE THREAD

**Issue by piotrgajow** [longwa/build-test-data#81]
Adding `@Build()` annotation with a class, which references an abstract domain class results in very long test execution time.

## How to reproduce:
1. Create abstract domain class `X`
2. Create regular domain class `Y` having field of type `X`
3. Create Spock Specification annotated with `@Build(Y)`
4. Running `gradle check` takes sometimes even more than 1 minute with empty test suite (no tests)

Exemplary source code reproducing issue can be found on: https://github.com/piotrgajow/Sandbox/tree/grails-BuildTestDataPlugin-AbstractIssue

Removing `abstract` keyword or `@Build` annotation reduces the time to a few seconds.

## Environment:
Plugin: 3.0.1
OS: Windows 10
Gradle: 3.4.1
Grails: 3.2.8
Groovy: 2.4.7
JVM: 1.8.0_131

**Comment by longwa** [comment]
This is a known issue and is caused by the ClassPath component scanning to find eligible subclasses. I have removed this functionality from the forthcoming 3.3.0 version for Grails 3.3+. Instead you will use the 'abstractDefaults' TestDataConfig block to define concrete subclasses for any Abstract classes you might need to build.

I'll try to back port this into the 3.0.x line as well.

**Comment by longwa** [comment]
The class path scanning has been removed in version 3.3.0+ so this is no longer an issue going forward.

**Comment by borgiani** [comment]
Hi @longwa, can you give an idea of when you think you'll be able to backport this to 3.0.x?
I have a project running on Grails 3.2.x that I can't upgrade to 3.3.x right now, and this issue is causing some of my CI builds to take up to 10 minutes longer than expected

**Comment by borgiani** [comment]
Suggested fix: #112
