### ISSUE TITLE
3.3.0.RC1 requires compile scope

### ISSUE THREAD

**Issue by erichelgeson** [longwa/build-test-data#96]
Just capturing our conversation from slack (so I can reference it in another project :) 

The plugin should work in the `testCompile` scope but currently does not. It does work however in the `compile` scope.

**Comment by basejump** [comment]
@erichelgeson can you give more info on the error you are seeing?

**Comment by erichelgeson** [comment]
given a class with this definition:

```groovy

@Build([Notification, Person])
class NotificationServiceSpec
        extends Specification
        implements UnitTestDataBuilder, ServiceUnitTest<NotificationService> {
```

I get 
```
No signature of method: x.y.Person.build() is applicable for argument types: (java.util.LinkedHashMap) values: [[password:foobar]]
```

When trying to build.

**Comment by basejump** [comment]
right, we just talked about that too. I may try to spin up some meta methods instead of using Traits for the build method. Your best bet though is to use the `build(Person)` methods in your tests vs `Person.build()` then the testCompile scope should work fine. If your like some of us and have 13,000 tests to refactor then I get need and conveniece of being able to use `Domain.build()` and not have to refactor all of them
